package entity;

public class Products {
	private String productId;
	private String productName;
	private double price;
	private int quantityAvailable;

	private static int Pid;
	static {
		Pid = 100;
	}

	public Products() {

	}

	public Products(String productName, double price, int quantityAvailable) {
		this.productId = "p" + ++Pid; // id autoGenerated number
		this.productName = productName;
		this.price = price;
		this.quantityAvailable = quantityAvailable;
	}

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public int getQuantityAvailable() {
		return quantityAvailable;
	}

	public void setQuantityAvailable(int quantityAvailable) {
		this.quantityAvailable = quantityAvailable;
	}

	@Override
	public String toString() {
		return "Products [productId=" + productId + ", productName=" + productName + ", price=" + price
				+ ", quantityAvailable=" + quantityAvailable + "]";
	}

}
